dist: xenial
os: linux
language: python
cache: pip
services:
- docker
python:
- 3.8
install:
# Make a wheel and install it
- pip install --upgrade setuptools pip
- pip install -r dev-requirements.txt
- python setup.py bdist_wheel
- pip install dist/*.whl
- pip freeze
script:
- |
  # run autoformat
  if [[ "$REPO_TYPE" == "lint" ]]; then
    pre-commit run --all-files
  fi
after_success:
- pip install codecov
- pushd tests && codecov && popd

after_failure:
- |
  # point to auto-lint-fix
  echo "You can install pre-commit hooks to automatically run formatting"
  echo "on each commit with:"
  echo "    pre-commit install"
  echo "or you can run by hand on staged files with"
  echo "    pre-commit run"
  echo "or after-the-fact on already committed files with"
  echo "    pre-commit run --all-files"
