channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - ipywidgets==7.6.3
  - jupyter-offlinenotebook==0.2.1
  - jupyter-resource-usage==0.6.0
  - jupyterlab==3.1.0
  - jupyterhub-singleuser==1.4.2
  - nbconvert==6.1.0
  - notebook==6.4.0
  - nteract_on_jupyter==2.1.3
